### ISSUE TITLE
Black render, black view [SHIFT + Z] ... Driver errors ... 

### ISSUE THREAD

**Issue by doohab** [ForgeXYZ/Arnold-For-Blender#10]
I get this ERROR multiple times:
|  [aov] output references a non-driver node: __driver

This error only occurs on switch to arnold render I guess:
-- node "driver_display_callback" is not installed

--  [aov] no valid output statements found: could be a progressive render without a display window

**Comment by furby-tm** [comment]
You have to add the driver to your `ArnoldSDK/plugins` folder

**Comment by doohab** [comment]
Oh, my mistake. I skipped this step unintentionally.
Thanks.
Works now.
