### ISSUE TITLE
Error on enabling arnold plugin

### ISSUE THREAD

**Issue by Sotty75** [ForgeXYZ/Arnold-For-Blender#13]
**Describe the bug**
After following all steps described in the readme file, i tried to enable the plugin and got the following error.

![image](https://user-images.githubusercontent.com/1228599/50356500-7337ba80-0552-11e9-8b09-7b6b2f79070e.png)

**To Reproduce**
1. Follow installation steps described in readme file.

**Expected behavior**
I expec the plugin to be enabled

**Screenshots**
![image](https://user-images.githubusercontent.com/1228599/50356513-8054a980-0552-11e9-9de2-d007a9363740.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
- Blender v2.79

**Additional context**

**Comment by furby-tm** [comment]
I can help you with this, first are you sure you want to use Blender 2.79? The Blender 2.8 version is the one actively in development, and has far more features.

**Comment by Sotty75** [comment]
Let me get the last version, will come back to you after that...
Thanks

Il giorno ven 21 dic 2018 alle ore 19:01 Tyler Furby <
notifications@github.com> ha scritto:

**Comment by Sotty75** [comment]
i did install it from steam, 2.8 looks to be still beta, i will get it
anyway from blender site.

Il giorno ven 21 dic 2018 alle ore 19:02 Paolo Sotgiu <
sotgiu.paolo@gmail.com> ha scritto:

**Comment by furby-tm** [comment]
The error that I can see is you're using the 2.8 version for blender 2.79, if you'd like to install arnold for Blender 2.79 You'll have to download that version from [here](https://github.com/tyler-furby/Arnold-For-Blender/tree/2.79l).

Otherwise I _highly_ recommend getting Blender 2.80 beta instead, it appears the devs won't be posting the 2.80 beta on steam, but you can download the Blender 2.80 beta [here](https://builder.blender.org/).

**Comment by Sotty75** [comment]
Getting it.
Thanks!!

Il giorno ven 21 dic 2018 alle ore 19:06 Tyler Furby <
notifications@github.com> ha scritto:

**Comment by furby-tm** [comment]
Great! Follow this checklist to ensure everything will install as planned:

- [ ] Download the [Blender 2.80 beta](https://builder.blender.org/) 

- [ ] Download the latest [Arnold for Blender Beta](https://github.com/tyler-furby/Arnold-For-Blender/tree/master)

- [ ] Download the latest [Arnold SDK](https://www.solidangle.com/arnold/download/#arnold-sdk)

- [ ] Move the `barnold` folder from the github repo to this folder `C:\Users\<YOUR USERNAME>\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\barnold`

- [ ] Overwrite the two `.py` files from `\Arnold SDK Adjustments\arnold` and replace the ones located in the `\ArnoldSDK\python\arnold` folder

- [ ] Add the `driver_display_callback.dll` from the `\Arnold SDK Adjustments\plugins` folder to the folder located in `ArnoldSDK\plugins`

- [ ] Add an environment variable to your `PATH` variable which will be the full file path on your machine to the `C:\ArnoldSDK\bin` folder (that's where I have mine)

- [ ] Add another environment variable on it's own called `ARNOLD_HOME` with it's full file path on your machine set to `C:\ArnoldSDK` (that's what I renamed mine to)

- [ ] Then restart your computer for those changes to take effect

**Comment by furby-tm** [comment]
The installation process is a bit tricky, and not everyone gets it the first time around, but I'm here if you need any more help, you can also join the [discord server](https://discord.gg/WNdNXzZ) where there is a community of people that will help you out, or if you'd like to become apart of the open source films at Wabi Studios, or just want to learn how to use Arnold in Blender! 

Feel free to let me know if you run into any issues.

Good luck!
