### ISSUE TITLE
Better contribution guidelines

### ISSUE THREAD

**Issue by melMass** [ForgeXYZ/Arnold-For-Blender#15]
Hi Tyler,

I want to get back at this now that I have fully shifted all my personal add-ons to 2.8.

The thing is I can't find any pieces of information regarding what is being worked on by priority etc...

Last time I pulled request for reviews and discussion you merged it to master while the work was not finished (preferences and finding Arnold path for all platforms.) I'd like to start by finishing that but wanted to make sure you are not actively working on that part.

Thanks

**Comment by furby-tm** [comment]
No problem!! No that would be perfect, can we chat on discord? It’d be easier to sort these things out over there

**Comment by thebarz** [comment]
I would love to chat on discord as well, but, the invitation link on the github shows invalid

**Comment by melMass** [comment]
@thebarz Barnold is actually being developed in a private branch now. This repo is the OSS version of the plugin that you can use as a fork, but further enhancements are private, targeting a commercial release by the end of this year.
Don't take my words for it as things might have shifted since last time I spoke to @tyler-furby
