### ISSUE TITLE
can not work

### ISSUE THREAD

**Issue by dororoholic** [ForgeXYZ/Arnold-For-Blender#16]
![Uploading image.png…]()

When I install, the following prompts appear

**Comment by dororoholic** [comment]
![image](https://user-images.githubusercontent.com/19920661/54743014-f3c39100-4bfd-11e9-8e97-1a2dcada9be9.png)

**Comment by Uewdl** [comment]
same issue too

**Comment by melMass** [comment]
@dororoholic @Uewdl Can you post the full log from the console?

**Comment by Uewdl** [comment]
in 2.79 version:
ATraceback（most recent call last）：File"：Nsetup\Blender Foundation\Blender\2.79\scripts\modules\addon_utils.py"，line 350，in enable mod.register（）
File“CA\Users\Goblin163cm\AppData\Roaming\Blender Foundation\Blender\2.79\scriptsladdons\barnold\_init.py"，line 160，in register from.import addon preferences File"C:\Users\Goblin163cm\AppData\Roaming\Blender Foundation\Blender\2.79\scriptsladdons\barnold\addon preferences.py"，line11
arnold_path:StringProperty（
SyntaxError:invalid syntax 
@melMass

**Comment by furby-tm** [comment]
@uewdl If you would like to use the 2.79 version, then you should download from the 2.79 branch - just note the 2.79 branch had stopped being maintained a while ago.

The current and latest version on the master branch is for blender 2.8 and above

**Comment by cgndev** [comment]
![image](https://user-images.githubusercontent.com/2674360/55772629-e9433b80-5ac7-11e9-86e6-4ad28ef5240f.png)

**Comment by furby-tm** [comment]
If you give it just 1 week, we will have the official beta release, complete with a full automatic installer, the IPR (rendered viewport) and more. Looking at a Saturday or Sunday release.

**Comment by 3dcinetv** [comment]
Hi Kang, this is Schiller (ex Softimager ICE pilot). I am glad to see you
in yhis group.

//// Awesome news to read about Arnold ready for Sunday!! Came early to the
party.

**Comment by furby-tm** [comment]
Support for Windows, Linux, macOS - AND, Arnold 5.2.x.x - 5.3.x.x. So you'll get all your GPU support as well :)

**Comment by jotero3d** [comment]
same issue too! Blender 2.8 finale + Arnold-5.4.0.0-windows.zip
sincerely Torolf

**Comment by furby-tm** [comment]
@jotero3d It's best not to use anything from this repo, it's quite a bit behind and lacks many features including the rendered viewport (IPR), Arnold nodes, UI along with GPU and optix denoising. We will be releasing here shortly, and highly advise on using that version instead. Almost everything in this repo is extremely broken.

**Comment by melMass** [comment]
@tyler-furby Do you have timeframe for the release ?

**Comment by jotero3d** [comment]
@tyler-furby Thank you for your quick response :)
