### ISSUE TITLE
Portal Light Toggle - Mesh Light in Barnold

### ISSUE THREAD

**Issue by okafor** [ForgeXYZ/Arnold-For-Blender#2]
Hi Tyler,

Please will you implement the light portal toggle on Quad Light per image attached for Arnold? - was going thru online manual. Thanks.

![portal_light_arnold](https://user-images.githubusercontent.com/457805/42296795-a241e602-7ff1-11e8-948d-5d1b51faa4b9.png)

regards
Ikem

**Comment by furby-tm** [comment]
Will do! Thank you.

**Comment by furby-tm** [comment]
Which docs are you following?

**Comment by furby-tm** [comment]
You should be following the Arnold for Maya documentation

**Comment by furby-tm** [comment]
At least until I get Barnold docs finished

**Comment by okafor** [comment]
Ok on use of Maya docs for Arnold. Was using the one for Max at https://support.solidangle.com/display/A5AF3DSUG/Quad+Light .

Thanks.

**Comment by furby-tm** [comment]
No problem, is everything working properly according to the Maya docs?

**Comment by okafor** [comment]
Seen a lot of changes since I slept ... very good. Will go through and report back. Thanks.

**Comment by furby-tm** [comment]
Open a new issue as you find more things! 👍
