### ISSUE TITLE
Node Texture - No update of color via node in viewport

### ISSUE THREAD

**Issue by okafor** [ForgeXYZ/Arnold-For-Blender#3]
1. Assign in nodes Standard Shader
2. Set viewport to shaded view
3. Change node diffuse color and check for change in viewport

Currently changes to Standard shader diffuse color is not reflected in blender viewport.

**Comment by furby-tm** [comment]
You mean Solid view?

**Comment by okafor** [comment]
Yes, Solid view.

**Comment by okafor** [comment]
Changes in color in node should affect the Solid view color but it stays white - anyways, it does not change color in Solid view.

**Comment by furby-tm** [comment]
Ah, sorry - You're saying nodes don't change the color in the viewport, but they do work in the material panel?

**Comment by okafor** [comment]
Yes ...

**Comment by furby-tm** [comment]
Yep, that's a bug - I'm working on that

**Comment by furby-tm** [comment]
Thank you, I'll keep this active until I fix it

**Comment by okafor** [comment]
Ok ...

**Comment by furby-tm** [comment]
Fixed in official.
