### ISSUE TITLE
Source code of the displayCallback driver ?

### ISSUE THREAD

**Issue by melMass** [ForgeXYZ/Arnold-For-Blender#4]
Hello,

It seems we need to be able to build the driver plugin from source for both Linux and OSX, would you share it in the repo ?

Thanks

**Comment by furby-tm** [comment]
Sure thing, here's the cpp file, be sure to link it to the ai.dll or equivalent on mac or linux.

https://www.dropbox.com/s/jptly2s6yzxveaq/driver_display_callback.cpp?dl=0

**Comment by furby-tm** [comment]
And after you compile it, would you mind sharing the compiled driver so I can post it on the repo for other people to use? Thanks!

**Comment by melMass** [comment]
I managed to build the driver on mac and render a frame in Blender.. well there seems to be a colorspace issue of some sort here is the result:

![](https://i.imgur.com/bzKT1JZ.jpg)

I'll dig more soon. 

Thanks for the source.

**Comment by furby-tm** [comment]
Awesome! I'll take a look, mind if you share the compiled drivers so I can do some tests? Thanks for taking a look into this.

**Comment by furby-tm** [comment]
Did you render in RGB or RGBA?

**Comment by melMass** [comment]
RGBA but I'll check in depth tomorrow.
Here is the build binary for Mac OS Sierra 10.12.6
[libbarnold_display_callback.dylib.zip](https://github.com/tyler-furby/barnold/files/2341792/libbarnold_display_callback.dylib.zip)

**Comment by furby-tm** [comment]
Added you as a contributor, thanks for your help.

**Comment by furby-tm** [comment]
Also, if you open blender in debug mode, and then enable all error messages in arnold settings, it might be able to pinpoint what's wrong.
