### ISSUE TITLE
Make ARNOLD_HOME cross platform

### ISSUE THREAD

**Issue by furby-tm** [ForgeXYZ/Arnold-For-Blender#6]
Change line 22 in __init__.py to append `ARNOLD_HOME` instead of the windows SDK for cross platform use. 

Needs to be a way to allow all OS's to make use of this import statement, `ARNOLD_HOME` wouldn't work for Windows, perhaps it's something I'm doing wrong?

**Comment by melMass** [comment]
I'm always running programs from the shell (I only use OSX and Linux) so I don't have those issues. 
I'm not sure about the windows side of things.
I think the best way to handle the SDK path situation would be to add a **path chooser** to the add-on's preferences. 

What do you think ?

**Comment by furby-tm** [comment]
I like it. Would you like to implement that?

**Comment by furby-tm** [comment]
Something like this? https://blender.stackexchange.com/questions/26898/how-to-create-a-folder-dialog

**Comment by furby-tm** [comment]
I gave you push access to make things easier.
