### ISSUE TITLE
Unable to enable the addon 

### ISSUE THREAD

**Issue by mistajuliax** [ForgeXYZ/Arnold-For-Blender#9]
Hi, i follow every step described in the installation. When i try to check the addon, blender crashes. I tried both on blender 2.79, and 2.8. I get the same issue. 
![arnold issue](https://user-images.githubusercontent.com/7542691/45163520-d9d9d800-b1f0-11e8-9268-38040accc1fa.jpg)

**Comment by furby-tm** [comment]
The issue is that the environment variable `ARNOLD_HOME` is not set to the Arnold SDK folder's path. Once you do that, it should load just fine.

**Comment by furby-tm** [comment]
Also, I will move the 2.8 version to it's own branch. The 2.8 api hasn't been completed yet, so Arnold doesn't work at all for that version yet

**Comment by mistajuliax** [comment]
I was thinking to do it the right way :( Does the path need to point out a particular file ? I extracted the sdk and add the path to this folder.

**Comment by furby-tm** [comment]
Can you send me what you have your path set to?

**Comment by StrobFX** [comment]
Same issue for me. I added the variable with this path:
C:\Arnold-5.2.0.1-windows

As soon as I click the barnold checkbox in Blender 2.79 blender crashes by disapearing.
I'm in windows 10

**Comment by mistajuliax** [comment]
@tyler-furby Hi, as soon as i go back home i will send you a print screen with enviroment variable and path i set up.
cheers.

**Comment by mistajuliax** [comment]
Hi, it's the way i set the path, am i wring ? ![barnold path](https://user-images.githubusercontent.com/7542691/45691862-b18b9b00-bb59-11e8-8721-9546afad3317.jpg)

**Comment by aditiapratama** [comment]
I''ve got the following error and crash
```
ARNOLD_HOME env found
Setting Arnold path to: C:\Arnold
Could not find ai.dll
Error: Not freed memory blocks: 149, total unfreed memory 0.407402 MB
```

**Comment by furby-tm** [comment]
You have to set both `PATH` and `Arnold_HOME`

**Comment by furby-tm** [comment]
`PATH` = `/arnoldSDK/bin` folder
`Arnold_HOME` = `/arnoldSDK/` folder

**Comment by aditiapratama** [comment]
> `PATH` = `/arnoldSDK/bin` folder
> `Arnold_HOME` = `/arnoldSDK/` folder

Gotcha, confirm it's works now
